# action.yml
name: 'Clone and Build Tests'
description: 'Clone and build a given repository'
inputs:
  compiler:  # compiler
    description: 'Compiler'
    required: false
    default: ''
  cpu:  # How much CPU do we use
    description: 'CPU Count'
    required: false
    default: '8'
  options:  # Special options
    description: 'Compiler options'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.compiler }}
    - ${{ inputs.cpu }}
    - ${{ inputs.options }}
