##======================================================================================================================
##  KIWAKU - Containers Well Made
##  Copyright : KIWAKU Project Contributors
##  SPDX-License-Identifier: BSL-1.0
##======================================================================================================================
name: Unit Tests
on:
  pull_request:
    branches:
      - main
concurrency:
  group: kiwaku-unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ##======================================================================================================================
  ## Preserve pre-commit checks
  ##======================================================================================================================
  precommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit checks
        run: pre-commit run --all-files --show-diff-on-failure --color=always

  ##======================================================================================================================
  ## Build and run unit tests
  ##======================================================================================================================
  linux-tests:
    name: Linux
    needs: precommit
    uses: ./.github/workflows/linux.yml

  macos-tests:
    name: MacOS
    needs: precommit
    uses: ./.github/workflows/macos.yml

  windows-tests:
    name: Windows
    needs: precommit
    uses: ./.github/workflows/windows.yml

  #nvidia-tests:
  #  name: Nvidia Unit Tests
  #  needs: precommit
  #  uses: ./.github/workflows/nvidia.yml
